		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "CVX",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0,0},
				gearRatios			= {0.26, 0.6, 1.0},
				autoRanges			= false,
				gearTexts			= {""},
				rangeTexts			= {"F1", "F2", "F3"} },
				reverseRanges		= {1},
				reverseRatio		= 1.27,
		text = "CVX Transmission" },
