		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "AUTOPWR",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0,0,0},
				gearRatios			= { 0.19, 0.388, 0.814, 1.000 },
				autoRanges			= false,
				gearTexts			= {""},
				rangeTexts			= { "schwerer Zug", "leichter Zug", "schwerer Transport", "leichter Transport" } },
			text = "6R AutoPwr"},
