		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "AUTPWRIVT",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0},
				gearRatios			= { 0.4425, 1.0000 },
				autoRanges			= false,
				gearTexts			= {""},
				rangeTexts			= { "Low-Max", "High-Max" } },
			text = "AutoPowr IVT"},
