		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "C-Matic",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0,0,0},
				gearRatios			= {0.1886, 0.3773, 0.566, 1.3773},
				autoRanges			= false,
				gearTexts			= {""},
				rangeTexts			= { "F1", "F2", "F3", "F4" }},
			text = "C-Matic Claas" },
