		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "HAR",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0},
				gearRatios			= { 0.4651, 1.2352 },
				autoRanges			= false,
				gearTexts			= {""},
				rangeTexts			= { "1", "2" } },
			text = "Pro Drive JD" },
