		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "HAR",
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {0},
				gearRatios			= { 0.5814, 1.2352 },
				autoRanges			= false,
				gearTexts			= {"1", "2"},
				rangeTexts			= { "" } },
			text = "Harvester Claas" },
