		{ class  = vehicleControlAddonTransmissionBase,
			params = { name			= "Vario T400",
				defaultClutch		= 1,
				isIVT				= true,
				noGears				= 1,
				rangeGearOverlap	= {},
				gearRatios			= { 1.0 },
				gearTexts			= {""},
				rangeTexts			= {""},
				reverseRatio		  =	0.55 },
			text = "Vario T400" },
